'use strict';
const $=id=>document.getElementById(id);
const ROUTE_KEY='routeWakeTest.savedRoute';
const TRIP_KEY='routeWakeTest.trip.v11.1';
const OLD_TRIP_KEY='routeWakeTest.trip.v11';
const SETTINGS_KEY='routeWakeTest.settings';
const CALC_HISTORY_KEY='routeWakeTest.timeCalculator.history.v11.1.3';
const TRIP_NAME_KEY='routeWakeTest.tripName';
const TRIPS_KEY='routeWakeTest.trips.v11.1.6';
const ACTIVE_TRIP_KEY='routeWakeTest.activeTrip.v11.1.6';
const state={route:[],stops:[],tripName:'',trips:[],activeTripId:'',currentStopIndex:0,currentPos:null,watchId:null,wakeLock:null,tracking:false,paused:false,lastFix:0,accuracy:null,heading:null,speed:null,sim:false,simRouteIndex:0,simDelay:0,pickMode:false,pickMarker:null,lastStatus:'未開始',log:[]};
let map,routeLine,currentMarker,accuracyCircle,stopLayer,nearestLayer,ageTimer,holdTimer,holdAnim,tapWakeArmed=false,tileLayer=null,tileErrors=0;
const els={tripName:$('tripName'),tripSlack:$('tripSlack'),gpsIndicator:$('gpsIndicator'),wakeIndicator:$('wakeIndicator'),voiceIndicator:$('voiceIndicator'),nextStopCard:$('nextStopCard'),nextStopName:$('nextStopName'),nextStopDistance:$('nextStopDistance'),etaText:$('etaText'),delayText:$('delayText'),tripCalcBtn:$('tripCalcBtn'),arriveBtn:$('arriveBtn'),quickAddBtn:$('quickAddBtn'),moreBtn:$('moreBtn'),recenterBtn:$('recenterBtn'),mapMessage:$('mapMessage'),pickBanner:$('pickBanner'),cancelPickBtn:$('cancelPickBtn'),drawer:$('drawer'),drawerBackdrop:$('drawerBackdrop'),drawerTitle:$('drawerTitle'),drawerHelp:$('drawerHelp'),drawerBody:$('drawerBody'),drawerClose:$('drawerClose'),simGpsQuality:$('simGpsQuality'),simDelay:$('simDelay'),exitSimBtn:$('exitSimBtn'),blackScreen:$('blackScreen'),blackStop:$('blackStop'),blackStatus:$('blackStatus'),blackWake:$('blackWake'),holdRing:$('holdRing')};
function log(msg){state.log.unshift(`[${new Date().toLocaleTimeString('zh-TW',{hour12:false})}] ${msg}`);state.log=state.log.slice(0,250)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function makeStop(name='未命名景點',lat=null,lon=null,note=''){return{id:crypto.randomUUID?.()||`s-${Date.now()}-${Math.random()}`,name,lat,lon,plannedArrival:'',stayMinutes:30,note,arrived:false,arrivedAt:null,temporary:false}}
function tripId(){return crypto.randomUUID?.()||`trip-${Date.now()}-${Math.random()}`}
function currentTripSnapshot(){return{id:state.activeTripId||tripId(),name:state.tripName||'未命名行程',route:state.route,stops:state.stops,currentStopIndex:state.currentStopIndex,paused:state.paused,updatedAt:Date.now()}}
function persistTrips(){localStorage.setItem(TRIPS_KEY,JSON.stringify(state.trips));localStorage.setItem(ACTIVE_TRIP_KEY,state.activeTripId||'')}
function syncActiveTrip(){if(!state.activeTripId)state.activeTripId=tripId();const snap=currentTripSnapshot(),i=state.trips.findIndex(t=>t.id===state.activeTripId);if(i>=0)state.trips[i]=snap;else state.trips.push(snap);persistTrips()}
function applyTrip(t){if(!t)return;state.activeTripId=t.id;state.tripName=t.name||'未命名行程';state.route=Array.isArray(t.route)?t.route:[];state.stops=Array.isArray(t.stops)?t.stops:[];state.currentStopIndex=Math.min(Number(t.currentStopIndex)||0,Math.max(0,state.stops.length-1));state.paused=!!t.paused;localStorage.setItem(ACTIVE_TRIP_KEY,state.activeTripId)}
function save(){syncActiveTrip();localStorage.setItem(ROUTE_KEY,JSON.stringify({version:11.1,points:state.route,savedAt:Date.now()}));localStorage.setItem(TRIP_KEY,JSON.stringify({version:11.1,stops:state.stops,currentStopIndex:state.currentStopIndex,paused:state.paused,tripName:state.tripName,updatedAt:Date.now()}));localStorage.setItem(TRIP_NAME_KEY,state.tripName||'')}
function load(){try{const lib=JSON.parse(localStorage.getItem(TRIPS_KEY)||'[]');if(Array.isArray(lib)&&lib.length){state.trips=lib;const active=localStorage.getItem(ACTIVE_TRIP_KEY);applyTrip(state.trips.find(t=>t.id===active)||state.trips[0]);return}const r=JSON.parse(localStorage.getItem(ROUTE_KEY)||'null');if(r?.points?.length)state.route=r.points;let t=JSON.parse(localStorage.getItem(TRIP_KEY)||'null');if(!t){const old=JSON.parse(localStorage.getItem(OLD_TRIP_KEY)||'null');if(old?.stops)t={...old,version:11.1}}if(t?.stops){state.stops=t.stops;state.tripName=t.tripName||localStorage.getItem(TRIP_NAME_KEY)||'未命名行程';state.currentStopIndex=Math.min(Number(t.currentStopIndex)||0,Math.max(0,state.stops.length-1));state.paused=!!t.paused}else state.tripName='未命名行程';state.activeTripId=tripId();state.trips=[currentTripSnapshot()];persistTrips()}catch(e){log(`讀取本機資料失敗：${e.message}`)}}
function initMap(){if(!window.L){els.mapMessage.textContent='地圖函式庫載入失敗；請檢查網路後重新整理。';els.mapMessage.classList.remove('hidden');return}map=L.map('map',{zoomControl:true,attributionControl:true}).setView([35.6812,139.7671],14);try{if(typeof L.maplibreGL==='function'){tileLayer=L.maplibreGL({style:'https://tiles.openfreemap.org/styles/liberty'}).addTo(map)}else throw new Error('MapLibre 綁定未載入')}catch(e){showMapMessage('向量底圖載入失敗；仍可使用路線、景點與定位','warn',6000);map.getContainer().classList.add('map-grid-fallback');log(`OpenFreeMap 失敗：${e.message}`)}routeLine=L.polyline([],{color:'#4f8ee8',weight:6,opacity:.85}).addTo(map);stopLayer=L.layerGroup().addTo(map);nearestLayer=L.layerGroup().addTo(map);map.on('click',e=>{if(state.pickMode)selectMapPoint(e.latlng.lat,e.latlng.lng)});renderMap(true)}
function divIcon(cls,label=''){return L.divIcon({className:'',html:`<div class="${cls}">${label?`<span>${esc(label)}</span>`:''}</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
function stopDistanceAndEta(i){const s=state.stops[i];if(!s)return{distance:'—',eta:'—',delayText:'尚無資料'};let d=Infinity;if(state.currentPos&&Number.isFinite(+s.lat)&&Number.isFinite(+s.lon))d=hav(state.currentPos,{lat:+s.lat,lon:+s.lon});const c=calcEta(d,s);return{distance:Number.isFinite(d)?formatDistance(d):'等待定位',eta:s.plannedArrival||c.eta||'未設定',delayText:s.plannedArrival?`預計抵達 ${s.plannedArrival}`:(c.eta!=='—'?`推估 ${c.eta}`:'未設定時間')}}
function openStopMapPopup(i,marker){const s=state.stops[i];if(!s)return;const info=stopDistanceAndEta(i),popup=L.popup({className:'stop-info-popup',closeButton:true,offset:[0,-8]}).setLatLng(marker.getLatLng()).setContent(`<div class="stop-popup"><strong>${i+1}. ${esc(s.name)}</strong><div class="stop-popup-metrics"><div><small>剩餘距離</small><b>${esc(info.distance)}</b></div><div><small>預計抵達</small><b>${esc(info.eta)}</b></div></div><div class="stop-popup-actions"><button data-popup-skip="${i}">跳過</button><button data-popup-remove="${i}" class="danger">移除</button><button data-popup-edit="${i}">編輯</button></div></div>`).openOn(map);setTimeout(()=>{const root=popup.getElement();if(!root)return;root.querySelector('[data-popup-skip]')?.addEventListener('click',()=>skipStopAt(i));root.querySelector('[data-popup-remove]')?.addEventListener('click',()=>deleteStopAt(i));root.querySelector('[data-popup-edit]')?.addEventListener('click',()=>{map.closePopup();openStopEditor(i)})},0)}
function skipStopAt(i){const s=state.stops[i];if(!s)return;s.arrived=true;s.arrivedAt=new Date().toISOString();if(i===state.currentStopIndex)advanceStop();save();map?.closePopup();renderMap();showMapMessage(`已跳過：${s.name}`,'ok',2500)}
function deleteStopAt(i){const s=state.stops[i];if(!s||!confirm(`移除「${s.name}」？`))return;state.stops.splice(i,1);if(i<state.currentStopIndex)state.currentStopIndex--;state.currentStopIndex=Math.min(Math.max(0,state.currentStopIndex),Math.max(0,state.stops.length-1));save();map?.closePopup();renderMap();showMapMessage(`已移除：${s.name}`,'ok',2500)}
function renderMap(fit=false){if(!map)return;routeLine.setLatLngs(state.route.map(p=>[p.lat,p.lon]));stopLayer.clearLayers();state.stops.forEach((s,i)=>{if(!Number.isFinite(+s.lat)||!Number.isFinite(+s.lon))return;const cls=i===state.currentStopIndex?'next-pin':'stop-pin';const m=L.marker([+s.lat,+s.lon],{icon:divIcon(cls,String(i+1))}).bindTooltip(`${i+1}. ${s.name}`);m.on('click',()=>openStopMapPopup(i,m));m.addTo(stopLayer)});if(state.currentPos){const ll=[state.currentPos.lat,state.currentPos.lon];if(!currentMarker)currentMarker=L.marker(ll,{icon:divIcon('current-pin'),zIndexOffset:1000}).addTo(map);else currentMarker.setLatLng(ll);if(!accuracyCircle)accuracyCircle=L.circle(ll,{radius:state.accuracy||0,color:'#2f8cff',fillColor:'#2f8cff',fillOpacity:.08,weight:1}).addTo(map);else accuracyCircle.setLatLng(ll).setRadius(state.accuracy||0)}if(fit){const pts=[...state.route,...state.stops.filter(s=>Number.isFinite(+s.lat)&&Number.isFinite(+s.lon))];if(pts.length)map.fitBounds(L.latLngBounds(pts.map(p=>[+p.lat,+p.lon])),{padding:[25,25]})}updateSummary()}
function parseXml(text){const d=new DOMParser().parseFromString(text,'application/xml');if(d.querySelector('parsererror'))throw new Error('XML 解析失敗');return d}
function textOf(n,tag){return n.getElementsByTagName(tag)[0]?.textContent?.trim()||''}
function simplify(points,max=5000){if(points.length<=max)return points;const step=Math.ceil(points.length/max);return points.filter((_,i)=>i%step===0||i===points.length-1)}
function parseGpx(text){const d=parseXml(text),points=[],stops=[];d.querySelectorAll('trkpt,rtept').forEach(n=>{const lat=+n.getAttribute('lat'),lon=+n.getAttribute('lon');if(Number.isFinite(lat)&&Number.isFinite(lon))points.push({lat,lon})});d.querySelectorAll('wpt').forEach(n=>{const lat=+n.getAttribute('lat'),lon=+n.getAttribute('lon');if(Number.isFinite(lat)&&Number.isFinite(lon))stops.push(makeStop(textOf(n,'name')||`景點 ${stops.length+1}`,lat,lon,textOf(n,'desc')))});return{points:simplify(points),stops}}
function parseKml(text){const d=parseXml(text),points=[],stops=[];d.querySelectorAll('LineString coordinates').forEach(n=>n.textContent.trim().split(/\s+/).forEach(t=>{const [lon,lat]=t.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon))points.push({lat,lon})}));d.querySelectorAll('Placemark').forEach(pm=>{const c=pm.querySelector('Point coordinates')?.textContent?.trim();if(!c)return;const [lon,lat]=c.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon))stops.push(makeStop(textOf(pm,'name')||`景點 ${stops.length+1}`,lat,lon,textOf(pm,'description')))});return{points:simplify(points),stops}}
function rad(v){return v*Math.PI/180}function hav(a,b){const R=6371000,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function nearestDistance(p){if(state.route.length<2)return Infinity;const lat0=rad(p.lat),R=6371000,xy=q=>({x:rad(q.lon)*R*Math.cos(lat0),y:rad(q.lat)*R}),pp=xy(p);let best=Infinity;for(let i=0;i<state.route.length-1;i++){const a=xy(state.route[i]),b=xy(state.route[i+1]),vx=b.x-a.x,vy=b.y-a.y,wx=pp.x-a.x,wy=pp.y-a.y,c=vx*vx+vy*vy,t=c?Math.max(0,Math.min(1,(vx*wx+vy*wy)/c)):0;best=Math.min(best,Math.hypot(pp.x-a.x-t*vx,pp.y-a.y-t*vy))}return best}
function getThresholds(){const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return{warn:+s.warnM||30,off:+s.offM||50,bad:+s.badM||80,walk:+s.walkSpeed||4}}
function setIndicator(el,level,title){el.className=`indicator ${level}`;if(title)el.title=title}
function gpsLevel(acc,age){if(!state.tracking&&!state.sim)return['idle','未開始'];if(age>30000)return['danger','定位過舊'];if(acc<=20)return['ok','定位良好'];if(acc<=50)return['warn','定位普通'];return['danger','定位不佳']}
function evaluateRoute(){if(!state.currentPos||state.route.length<2)return{label:'尚無判斷',level:'idle',distance:Infinity};const d=nearestDistance(state.currentPos),t=getThresholds();if(d>=t.bad)return{label:'嚴重偏離',level:'danger',distance:d};if(d>=t.off)return{label:'偏離路線',level:'danger',distance:d};if(d>=t.warn)return{label:'接近偏離門檻',level:'warn',distance:d};return{label:'路線正常',level:'ok',distance:d}}
function updateSummary(){const stop=state.stops[state.currentStopIndex];els.tripName.textContent=state.tripName||'未命名行程';els.nextStopName.textContent=stop?.name||'尚未設定';let dist=Infinity;if(stop&&state.currentPos&&Number.isFinite(+stop.lat)&&Number.isFinite(+stop.lon))dist=hav(state.currentPos,{lat:+stop.lat,lon:+stop.lon});els.nextStopDistance.textContent=Number.isFinite(dist)?formatDistance(dist):'—';const calc=calcEta(dist,stop);els.etaText.textContent=calc.eta;els.delayText.textContent=calc.delayText;els.delayText.style.color=calc.delay>8?'var(--danger)':calc.delay>3?'var(--warn)':'';els.tripSlack.textContent=!stop?.plannedArrival?'時間餘裕：未設定截止時間':calc.delay>0?`時間不足 ${calc.delay} 分鐘`:calc.delay<-3?`時間餘裕 ${Math.abs(calc.delay)} 分鐘`:'時間餘裕：接近準時';els.tripSlack.className=calc.delay>8?'bad':calc.delay>3?'warn':'ok';els.blackStop.textContent=`下一站：${stop?.name||'—'}`;els.nextStopCard.classList.toggle('paused',state.paused);const age=state.lastFix?Date.now()-state.lastFix:Infinity,[gl,gt]=gpsLevel(state.accuracy??999,age);setIndicator(els.gpsIndicator,gl,gt);const ev=evaluateRoute();els.blackStatus.textContent=state.paused?'行程已暫停':ev.label;if(state.currentPos&&ev.label!==state.lastStatus&&!state.paused&&Date.now()>(state.simVoiceOverrideUntil||0)){if(ev.label.includes('偏離'))speak(ev.label);else if(state.lastStatus.includes('偏離')&&ev.label==='路線正常')speak('回到路線');state.lastStatus=ev.label}if(state.pickMode)return;showMapMessage(state.paused?'行程已暫停':ev.label,ev.level,1500)}
function calcEta(distance,stop){if(!Number.isFinite(distance))return{eta:'—',delay:0,delayText:stop?.plannedArrival?'等待位置':'尚無時間資料'};const speed=Math.max(.5,state.speed&&state.speed>0.3?state.speed*3.6:getThresholds().walk);const mins=distance/1000/speed*60;const etaDate=new Date(Date.now()+mins*60000+state.simDelay*60000);const eta=etaDate.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false});if(!stop?.plannedArrival)return{eta,delay:0,delayText:`約 ${Math.ceil(mins)} 分鐘`};const [h,m]=stop.plannedArrival.split(':').map(Number),planned=new Date();planned.setHours(h,m,0,0);let delay=Math.round((etaDate-planned)/60000);return{eta,delay,delayText:delay>0?`落後約 ${delay} 分鐘`:delay<-3?`提早約 ${Math.abs(delay)} 分鐘`:'大致準時'}}
function formatDistance(m){return m>=1000?`${(m/1000).toFixed(1)} km`:`${Math.round(m)} m`}
function showMapMessage(text,level='idle',ms=2500){els.mapMessage.textContent=text;els.mapMessage.style.borderColor=level==='danger'?'#a94b4b':level==='warn'?'#8c742b':'#444';els.mapMessage.classList.remove('hidden');clearTimeout(showMapMessage.t);showMapMessage.t=setTimeout(()=>els.mapMessage.classList.add('hidden'),ms)}
function speak(text){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';speechSynthesis.cancel();speechSynthesis.speak(u)}
function onPosition(pos){state.sim=false;state.lastFix=Date.now();state.currentPos={lat:pos.coords.latitude,lon:pos.coords.longitude};state.accuracy=pos.coords.accuracy;state.heading=pos.coords.heading;state.speed=pos.coords.speed;renderMap();if(state.tracking&&!state.wakeLock)armWakeTap('GPS 更新後')}
function onGeoError(e){log(`定位錯誤：${e.code} ${e.message}`);setIndicator(els.gpsIndicator,'danger','定位錯誤');showMapMessage('無法取得定位','danger',4000)}
async function startTracking(){if(state.watchId!=null)return;state.tracking=true;state.paused=false;save();if(!navigator.geolocation){alert('瀏覽器不支援定位');return}await requestWake('開始定位');state.watchId=navigator.geolocation.watchPosition(onPosition,onGeoError,{enableHighAccuracy:true,maximumAge:1000,timeout:15000});ageTimer=setInterval(updateSummary,5000);log('開始真實 GPS 定位')}
async function stopTracking(){state.tracking=false;if(state.watchId!=null)navigator.geolocation.clearWatch(state.watchId);state.watchId=null;clearInterval(ageTimer);if(state.wakeLock){const w=state.wakeLock;state.wakeLock=null;await w.release().catch(()=>{})}setIndicator(els.wakeIndicator,'idle','未啟用');els.blackWake.textContent='Wake Lock：未啟用';log('停止定位並釋放 Wake Lock')}
async function requestWake(reason='手動'){if(!('wakeLock'in navigator)){setIndicator(els.wakeIndicator,'danger','不支援');return false}if(document.visibilityState!=='visible')return false;if(state.wakeLock)return true;try{state.wakeLock=await navigator.wakeLock.request('screen');setIndicator(els.wakeIndicator,'ok','已啟用');els.blackWake.textContent='Wake Lock：已啟用';state.wakeLock.addEventListener('release',()=>{state.wakeLock=null;setIndicator(els.wakeIndicator,state.tracking?'warn':'idle',state.tracking?'點一下螢幕啟用':'未啟用');if(state.tracking)armWakeTap('釋放後')},{once:true});log(`Wake Lock 已啟用（${reason}）`);return true}catch(e){setIndicator(els.wakeIndicator,'warn','點一下螢幕啟用');armWakeTap(reason);log(`Wake Lock 失敗：${e.name}`);return false}}
function armWakeTap(reason){if(tapWakeArmed||state.wakeLock||!state.tracking)return;tapWakeArmed=true;const h=()=>{tapWakeArmed=false;document.removeEventListener('pointerdown',h,true);requestWake(`${reason}／使用者手勢`)};document.addEventListener('pointerdown',h,true)}
function openDrawer(title,html,after){els.drawerTitle.textContent=title;els.drawerBody.innerHTML=html;els.drawer.classList.remove('hidden');els.drawerBackdrop.classList.remove('hidden');els.drawerHelp.classList.add('hidden');els.drawerHelp.onclick=null;after?.()}
function closeDrawer(){els.drawer.classList.add('hidden');els.drawerBackdrop.classList.add('hidden');els.drawerBody.innerHTML='';els.drawerHelp.classList.add('hidden');els.drawerHelp.onclick=null}
els.drawerClose.onclick=closeDrawer;els.drawerBackdrop.onclick=closeDrawer;
function openMore(){openDrawer('更多功能',$('moreTemplate').innerHTML,()=>els.drawerBody.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>handleMenu(b.dataset.menu)))}
function handleMenu(k){if(k==='trip')openTripPanel();if(k==='stops')openStopsPanel();if(k==='gps')openGpsPanel();if(k==='settings')openSettings();if(k==='backup')openBackup();if(k==='about')openAbout();if(k==='black'){closeDrawer();enterBlack()}if(k==='end')openEndPanel()}
function tripCardsHtml(action='select'){return state.trips.map(t=>`<article class="trip-card ${t.id===state.activeTripId?'current':''}"><div><strong>${esc(t.name||'未命名行程')}</strong><small>${(t.stops||[]).length} 個景點｜${(t.route||[]).length} 個路線點${t.id===state.activeTripId?'｜目前使用中':''}</small></div><div class="trip-card-actions"><button data-trip-open="${esc(t.id)}">${action==='manage'?'管理景點':'切換'}</button><button data-trip-rename="${esc(t.id)}">改名</button><button data-trip-delete="${esc(t.id)}" class="danger-text">刪除</button></div></article>`).join('')||'<p class="note">尚無行程。</p>'}
function bindTripCardActions(action='select'){els.drawerBody.querySelectorAll('[data-trip-open]').forEach(b=>b.onclick=()=>{const t=state.trips.find(x=>x.id===b.dataset.tripOpen);if(!t)return;if(action==='manage'){applyTrip(t);openStopsForTrip(t.id)}else{syncActiveTrip();applyTrip(t);renderMap(true);closeDrawer();showMapMessage(`已切換行程：${t.name}`,'ok',3000)}});els.drawerBody.querySelectorAll('[data-trip-rename]').forEach(b=>b.onclick=()=>{const t=state.trips.find(x=>x.id===b.dataset.tripRename),name=prompt('行程名稱',t?.name||'');if(!t||!name?.trim())return;t.name=name.trim();if(t.id===state.activeTripId)state.tripName=t.name;persistTrips();openTripPanel()});els.drawerBody.querySelectorAll('[data-trip-delete]').forEach(b=>b.onclick=()=>{const t=state.trips.find(x=>x.id===b.dataset.tripDelete);if(!t||!confirm(`刪除行程「${t.name}」？`))return;if(state.trips.length===1)return alert('至少保留一個行程。');state.trips=state.trips.filter(x=>x.id!==t.id);if(t.id===state.activeTripId)applyTrip(state.trips[0]);persistTrips();renderMap(true);openTripPanel()})}
function openTripPanel(){syncActiveTrip();openDrawer('行程列表',`<div class="button-row"><label class="file-btn">匯入為新行程<input id="routeInput" type="file" accept=".gpx,.kml,text/xml,application/xml"></label><button id="newBlankTrip">建立空白行程</button></div><p class="note">匯入檔案會建立另一個行程，不會覆蓋目前行程。</p><div class="trip-list">${tripCardsHtml('select')}</div>`,()=>{bindTripCardActions('select');$('newBlankTrip').onclick=()=>{syncActiveTrip();const t={id:tripId(),name:`新行程 ${state.trips.length+1}`,route:[],stops:[],currentStopIndex:0,paused:false,updatedAt:Date.now()};state.trips.push(t);applyTrip(t);persistTrips();renderMap(true);openTripPanel()};$('routeInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=f.name.toLowerCase().endsWith('.kml')?parseKml(await f.text()):parseGpx(await f.text()),t={id:tripId(),name:f.name.replace(/\.(gpx|kml)$/i,''),route:data.points,stops:data.stops,currentStopIndex:0,paused:false,updatedAt:Date.now()};syncActiveTrip();state.trips.push(t);applyTrip(t);persistTrips();renderMap(true);openTripPanel();showMapMessage(`已新增行程：${t.name}`,'ok',4000)}catch(err){alert(err.message)}}})}
function openStopsPanel(){syncActiveTrip();openDrawer('選擇要管理的行程',`<p class="note">先選擇行程，再進入該行程的景點清單。</p><div class="trip-list">${tripCardsHtml('manage')}</div>`,()=>bindTripCardActions('manage'))}
function openStopsForTrip(id){const t=state.trips.find(x=>x.id===id);if(!t)return;applyTrip(t);const cards=state.stops.map((s,i)=>`<article class="stop-card ${i===state.currentStopIndex?'current':''} ${s.arrived?'arrived':''}"><div class="stop-head"><span>${i+1}</span><strong>${esc(s.name)}</strong><button data-edit="${i}">編輯</button></div><div class="stop-meta">${s.plannedArrival||'未設定時間'}｜停留 ${s.stayMinutes||0} 分鐘${s.temporary?'｜臨時':''}</div></article>`).join('')||'<p class="note">目前沒有景點。</p>';openDrawer(`景點清單｜${t.name}`,`<div class="button-row"><button id="backTrips">返回行程列表</button><button id="addFromList">新增景點</button><button id="resetArrived">重設抵達狀態</button></div><div class="stop-list">${cards}</div>`,()=>{els.drawerBody.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openStopEditor(+b.dataset.edit));$('backTrips').onclick=openStopsPanel;$('addFromList').onclick=openAddChoice;$('resetArrived').onclick=()=>{state.stops.forEach(s=>{s.arrived=false;s.arrivedAt=null});state.currentStopIndex=0;save();openStopsForTrip(state.activeTripId);renderMap()}})}
function openStopEditor(i){const s=state.stops[i];if(!s)return;openDrawer('編輯景點',`<div class="editor-coordinate">${Number.isFinite(+s.lat)?(+s.lat).toFixed(6):'—'}, ${Number.isFinite(+s.lon)?(+s.lon).toFixed(6):'—'}</div><div class="form-grid"><label>名稱<input id="eName" value="${esc(s.name)}"></label><label>預計抵達<div class="field-with-action"><input id="eArrival" type="time" value="${esc(s.plannedArrival)}"><button id="editArrivalCalc" type="button">時間計算</button></div></label><label>停留分鐘<input id="eStay" type="number" min="0" value="${+s.stayMinutes||0}"></label><label>備註<textarea id="eNote">${esc(s.note||'')}</textarea></label></div><div class="button-row"><button id="saveStop">儲存</button><button id="setCurrent">設為下一站</button><button id="changeStopLocation">變更位置</button><button id="skipEditStop">本次跳過</button><button id="deleteEditStop" class="danger">移除景點</button><a href="${googleUrl(s)}" target="_blank" rel="noopener">Google 地圖</a></div>`,()=>{const saveEditorValues=()=>{s.name=$('eName').value.trim()||'未命名景點';s.plannedArrival=$('eArrival').value;s.stayMinutes=Math.max(0,+$('eStay').value||0);s.note=$('eNote').value};$('editArrivalCalc').onclick=()=>{saveEditorValues();openCalculator({title:`設定「${s.name}」抵達時間`,initialTime:s.plannedArrival,timeFieldMode:true,applyLabel:'套用為預計抵達',onApply:time=>{s.plannedArrival=time;save();renderMap();openStopEditor(i)}})};$('saveStop').onclick=()=>{saveEditorValues();save();renderMap();openStopsForTrip(state.activeTripId)};$('setCurrent').onclick=()=>{saveEditorValues();state.currentStopIndex=i;save();renderMap();closeDrawer()};$('changeStopLocation').onclick=()=>{saveEditorValues();closeDrawer();startPickMode({editIndex:i})};$('skipEditStop').onclick=()=>{saveEditorValues();skipStopAt(i);openStopsForTrip(state.activeTripId)};$('deleteEditStop').onclick=()=>{saveEditorValues();deleteStopAt(i);openStopsForTrip(state.activeTripId)}})}
function openAddChoice(){openDrawer('臨時新增景點',`<p class="note">選擇取得景點位置的方式。</p><div class="choice-stack"><button id="addByMap" class="action-btn">點擊地圖</button><button id="addByInput" class="action-btn">輸入／Google 地圖查找</button></div>`,()=>{$('addByMap').onclick=()=>{closeDrawer();startPickMode({mode:'add'})};$('addByInput').onclick=openLocationInput})}
function openLocationInput(){openDrawer('輸入景點位置',`<p class="note">可貼上：完整 Plus Code、短 Plus Code＋地區名稱、含座標的 Google 地圖網址，或「緯度,經度」。短 Plus Code 需要連線查找地區位置。</p><div class="button-row"><a href="https://www.google.com/maps/search/?api=1&query=" target="_blank" rel="noopener">開啟 Google 地圖搜尋</a></div><div class="form-grid"><label>Google 地圖資料／Plus Code／座標<textarea id="locationInput" placeholder="例如：4M8H+4V 大明里 臺中市大里區"></textarea></label></div><div class="button-row"><button id="parseLocation" class="primary-action">解析並繼續</button></div>`,()=>{$('parseLocation').onclick=async()=>{const raw=$('locationInput').value.trim();if(!raw)return alert('請先貼上位置資料');const btn=$('parseLocation');btn.disabled=true;btn.textContent='解析中…';try{let pos=parseGoogleLocation(raw);if(!pos)pos=await decodePlusCodeInput(raw);openAddDetails(pos)}catch(e){alert(e.message||'無法解析位置')}finally{btn.disabled=false;btn.textContent='解析並繼續'}}})}
function parseShortCodeParts(input){const raw=String(input||'').trim();const m=raw.toUpperCase().match(/([23456789CFGHJMPQRVWX]{2,7}\+[23456789CFGHJMPQRVWX]{2,7})/);if(!m)return null;const locality=(raw.slice(0,m.index)+' '+raw.slice(m.index+m[0].length)).replace(/[,，]/g,' ').replace(/\s+/g,' ').trim();return{code:m[1],locality}}
async function geocodeLocality(text){if(!text)throw new Error('短 Plus Code 必須附上鄉鎮、市區或城市名稱。');const url='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(text);const r=await fetch(url,{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error('地區位置查詢失敗，請稍後再試。');const a=await r.json();if(!a?.length)throw new Error('找不到附帶的地區名稱，請改貼完整 Plus Code 或座標。');return{lat:+a[0].lat,lon:+a[0].lon}}
function recoverNearestShortCode(shortCode,ref){const alphabet='23456789CFGHJMPQRVWX';let code=shortCode.toUpperCase().replace(/\s+/g,'');const sep=code.indexOf('+');if(sep<0||sep>=8)throw new Error('短 Plus Code 格式不正確。');const missing=8-sep;const fullRef=encodePlusCode(ref.lat,ref.lon,10);code=fullRef.slice(0,missing)+code;const area=decodePlusCode(code);const resolution=Math.pow(20,2-Math.floor(missing/2));let lat=area.lat,lon=area.lon;lat+=Math.round((ref.lat-lat)/resolution)*resolution;lon+=Math.round((ref.lon-lon)/resolution)*resolution;if(lat>90)lat-=resolution;if(lat<-90)lat+=resolution;return{lat,lon}}
function encodePlusCode(lat,lon,length=10){const alphabet='23456789CFGHJMPQRVWX',res=[20,1,.05,.0025,.000125];lat=Math.min(90,Math.max(-90,+lat));lon=((+lon+180)%360+360)%360-180;let la=lat+90,lo=lon+180,out='';for(let i=0;i<5;i++){const r=res[i],a=Math.floor(la/r),b=Math.floor(lo/r);out+=alphabet[a]+alphabet[b];la-=a*r;lo-=b*r}return out.slice(0,8)+'+'+out.slice(8,length)}
async function decodePlusCodeInput(input){const raw=String(input||'').trim();const full=raw.toUpperCase().match(/[23456789CFGHJMPQRVWX0]{8}\+[23456789CFGHJMPQRVWX]{2,7}/);if(full)return decodePlusCode(full[0]);const parts=parseShortCodeParts(raw);if(!parts)throw new Error('找不到可辨識的 Plus Code。');let ref=state.currentPos;if(!ref&&state.route?.length){const p=state.route[Math.floor(state.route.length/2)];ref={lat:+p.lat,lon:+p.lon}}if(!ref)ref=await geocodeLocality(parts.locality);else if(parts.locality){try{ref=await geocodeLocality(parts.locality)}catch{}}
return recoverNearestShortCode(parts.code,ref)}
function promptPlusCode(){const code=prompt('輸入 Plus Code；短碼請連同地區名稱一起貼上。');if(!code)return;decodePlusCodeInput(code).then(p=>{$('aLat').value=p.lat.toFixed(6);$('aLon').value=p.lon.toFixed(6);map.setView([p.lat,p.lon],17)}).catch(e=>alert(e.message))}
function decodePlusCode(input){let raw=String(input||'').toUpperCase().trim();const match=raw.match(/[23456789CFGHJMPQRVWX0]{8}\+[23456789CFGHJMPQRVWX]{2,7}/);if(match)raw=match[0];raw=raw.replace(/\s+/g,'');const alphabet='23456789CFGHJMPQRVWX',sep=raw.indexOf('+');if(sep!==8)throw new Error('這不是完整 Plus Code。');const before=raw.slice(0,sep),after=raw.slice(sep+1);if(!after.length)throw new Error('Plus Code 加號後缺少定位字元。');if(before.includes('0'))throw new Error('目前不接受補零格式的 Plus Code。');const clean=before+after;if(!/^[23456789CFGHJMPQRVWX]+$/.test(clean))throw new Error('Plus Code 含有無效字元。');const resolutions=[20,1,.05,.0025,.000125];let lat=-90,lon=-180,pairs=Math.min(5,Math.floor(clean.length/2)),latSize=20,lonSize=20;for(let i=0;i<pairs;i++){const res=resolutions[i],a=alphabet.indexOf(clean[i*2]),b=alphabet.indexOf(clean[i*2+1]);lat+=a*res;lon+=b*res;latSize=res;lonSize=res}if(clean.length>10){latSize=resolutions[4];lonSize=resolutions[4];for(let i=10;i<clean.length;i++){const n=alphabet.indexOf(clean[i]);latSize/=5;lonSize/=4;lat+=Math.floor(n/4)*latSize;lon+=(n%4)*lonSize}}return{lat:Math.min(90,lat+latSize/2),lon:Math.min(180,lon+lonSize/2)}}
function insertPositionOptionsHtml(){const stops=state.stops;if(!stops.length)return'<option value="0">加到行程最後</option>';const cur=Math.min(Math.max(0,state.currentStopIndex),stops.length);const opts=[];opts.push({value:cur,label:cur<stops.length?`設為下一站・插在第 ${cur+1} 站「${esc(stops[cur].name)}」之前`:'設為下一站・加到行程最後'});for(let i=0;i<stops.length;i++)opts.push({value:i+1,label:`插在第 ${i+1} 站「${esc(stops[i].name)}」之後`});opts.push({value:stops.length,label:'加到行程最後'});return opts.map(o=>`<option value="${o.value}" ${o.value===cur?'selected':''}>${o.label}</option>`).join('')}
function shiftAddArrival(mins){const el=$('aArrival');if(!el)return;const base=el.value?dateFromTime(el.value):new Date();base.setMinutes(base.getMinutes()+mins);el.value=timeValue(base);el.focus()}
function openAddDetails(prefill={}){openDrawer('新增景點資料',`<div class="editor-coordinate">${(+prefill.lat).toFixed(6)}, ${(+prefill.lon).toFixed(6)}</div><div class="form-grid"><label>景點名稱<input id="aName" value="${esc(prefill.name||'')}"></label><label>插入位置<select id="aInsert">${insertPositionOptionsHtml()}</select></label><label>預計抵達<div class="time-input-wrap"><input id="aArrival" class="time-native" type="time" step="60"></div><div class="button-row compact-row quick-add-shift"><button type="button" data-add-shift="-10">-10</button><button type="button" data-add-shift="-5">-5</button><button type="button" data-add-shift="5">+5</button><button type="button" data-add-shift="10">+10</button></div></label><div class="button-row compact-row"><button id="arrivalNow" type="button">目前時間</button><button id="arrivalClear" type="button">清除時間</button></div><label>停留分鐘<input id="aStay" type="number" value="30" min="0"></label><label><input id="aPermanent" type="checkbox"> 永久加入行程範本</label></div><div class="button-row"><button id="saveAdd" class="primary-action">確認加入</button></div>`,()=>{$('aArrival').disabled=false;$('arrivalNow').onclick=()=>{$('aArrival').value=timeValue(new Date());$('aArrival').focus()};$('arrivalClear').onclick=()=>{$('aArrival').value='';$('aArrival').focus()};document.querySelectorAll('[data-add-shift]').forEach(b=>b.onclick=()=>shiftAddArrival(+b.dataset.addShift));$('saveAdd').onclick=()=>{const s=makeStop($('aName').value.trim()||'臨時景點',+prefill.lat,+prefill.lon,'');s.plannedArrival=$('aArrival').value||'';s.stayMinutes=Math.max(0,+$('aStay').value||0);s.temporary=!$('aPermanent').checked;const pos=Math.max(0,Math.min(+$('aInsert').value||0,state.stops.length));state.stops.splice(pos,0,s);save();renderMap();closeDrawer();showMapMessage('已加入景點','ok')}})}
function startPickMode(context={mode:'add'}){state.pickContext=context;state.pickMode=true;els.pickBanner.classList.remove('hidden');map.getContainer().style.cursor='crosshair'}function stopPickMode(){state.pickMode=false;els.pickBanner.classList.add('hidden');map.getContainer().style.cursor='';if(state.pickMarker){map.removeLayer(state.pickMarker);state.pickMarker=null}}
function selectMapPoint(lat,lon){if(state.pickMarker)map.removeLayer(state.pickMarker);state.pickMarker=L.marker([lat,lon],{icon:divIcon('pick-pin')}).addTo(map);const context=state.pickContext||{mode:'add'};stopPickMode();if(Number.isInteger(context.editIndex)){const s=state.stops[context.editIndex];s.lat=lat;s.lon=lon;save();renderMap();openStopEditor(context.editIndex);showMapMessage('景點位置已更新','ok')}else openAddDetails({lat,lon})}
els.cancelPickBtn.onclick=stopPickMode;
function promptPlusCode(){const code=prompt('輸入完整 Plus Code（例如 8Q7XMPM5+32）');if(!code)return;try{const p=decodePlusCode(code);$('aLat').value=p.lat.toFixed(6);$('aLon').value=p.lon.toFixed(6);map.setView([p.lat,p.lon],17)}catch(e){alert(e.message)}}
function decodePlusCode(input){let raw=String(input||'').toUpperCase().trim();const match=raw.match(/[23456789CFGHJMPQRVWX0]{8}\+[23456789CFGHJMPQRVWX]{2,7}/);if(match)raw=match[0];raw=raw.replace(/\s+/g,'');const alphabet='23456789CFGHJMPQRVWX',sep=raw.indexOf('+');if(sep!==8)throw new Error('需要完整 Plus Code；加號前應有 8 個字元。');const before=raw.slice(0,sep),after=raw.slice(sep+1);if(!after.length)throw new Error('Plus Code 加號後缺少定位字元。');if(before.includes('0'))throw new Error('目前僅接受未縮短、未補零的完整 Plus Code。');const clean=before+after;if(!/^[23456789CFGHJMPQRVWX]+$/.test(clean))throw new Error('Plus Code 含有無效字元。');const resolutions=[20,1,.05,.0025,.000125];let lat=-90,lon=-180,pairs=Math.min(5,Math.floor(clean.length/2)),latSize=20,lonSize=20;for(let i=0;i<pairs;i++){const res=resolutions[i],a=alphabet.indexOf(clean[i*2]),b=alphabet.indexOf(clean[i*2+1]);lat+=a*res;lon+=b*res;latSize=res;lonSize=res}if(clean.length>10){latSize=resolutions[4];lonSize=resolutions[4];for(let i=10;i<clean.length;i++){const n=alphabet.indexOf(clean[i]);latSize/=5;lonSize/=4;lat+=Math.floor(n/4)*latSize;lon+=(n%4)*lonSize}}lat=Math.min(90,lat+latSize/2);lon=Math.min(180,lon+lonSize/2);return{lat,lon}}
function parseGoogleLocation(t){let m=t.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/)||t.match(/[?&](?:query|q)=(-?\d+\.\d+)%2C(-?\d+\.\d+)/i)||t.match(/(-?\d+\.\d+)\s*[,，]\s*(-?\d+\.\d+)/);if(m)return{lat:+m[1],lon:+m[2]};return null}
function googleUrl(s){return Number.isFinite(+s.lat)&&Number.isFinite(+s.lon)?`https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lon}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name)}`}
function openRemovePanel(){const opts=state.stops.map((s,i)=>`<option value="${i}" ${i===state.currentStopIndex?'selected':''}>${i+1}. ${esc(s.name)}</option>`).join('');openDrawer('移除或跳過景點',`<div class="form-grid"><label>選擇景點<select id="removeIndex">${opts}</select></label><p class="note">「跳過」只改變本次進度；「移除」會從目前保存的行程資料刪除。</p></div><div class="button-row"><button id="skipStop">本次跳過</button><button id="deleteStop" class="danger">移除景點</button></div>`,()=>{$('skipStop').onclick=()=>{skipStopAt(+$('removeIndex').value);closeDrawer()};$('deleteStop').onclick=()=>{deleteStopAt(+$('removeIndex').value);closeDrawer()}})}
function timeValue(date=new Date()){return date.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}
function dateFromTime(value){const d=new Date(),m=/^(\d{1,2}):(\d{2})$/.exec(value||'');if(m)d.setHours(+m[1],+m[2],0,0);else d.setSeconds(0,0);return d}
function shiftTimeInput(minutes,context=null){const el=$('cBaseTime');if(!el)return;const d=dateFromTime(el.value);d.setMinutes(d.getMinutes()+minutes);el.value=timeValue(d);renderCalculatorPreview(context)}
function loadCalcHistory(){try{const h=JSON.parse(localStorage.getItem(CALC_HISTORY_KEY)||'[]');return Array.isArray(h)?h:[]}catch{return[]}}
function saveCalcHistory(item){const history=loadCalcHistory();history.unshift(item);localStorage.setItem(CALC_HISTORY_KEY,JSON.stringify(history.slice(0,30)))}
function deadlineTargetDate(value,dayOffset=0){const target=dateFromTime(value);target.setDate(target.getDate()+Math.max(0,+dayOffset||0));return target}
function minutesUntilTime(value,dayOffset=0){const now=new Date(),target=deadlineTargetDate(value,dayOffset);return Math.round((target-now)/60000)}
function remainingPlan(targetIndex){const walk=Math.max(.5,getThresholds().walk),startIndex=Math.max(0,state.currentStopIndex),endIndex=Math.max(startIndex,Math.min(+targetIndex||startIndex,state.stops.length-1));let prev=state.currentPos&&Number.isFinite(state.currentPos.lat)?state.currentPos:null,totalDistance=0,stay=0;const legs=[];for(let i=startIndex;i<=endIndex;i++){const stop=state.stops[i];if(!stop||!Number.isFinite(+stop.lat)||!Number.isFinite(+stop.lon))continue;let d=0;if(prev)d=hav(prev,{lat:+stop.lat,lon:+stop.lon});totalDistance+=d;const stopStay=i<endIndex?Math.max(0,+stop.stayMinutes||0):0;stay+=stopStay;legs.push({index:i,name:stop.name,distance:d,stay:stopStay});prev={lat:+stop.lat,lon:+stop.lon}}const walking=totalDistance/1000/walk*60;return{startIndex,endIndex,totalDistance,walking,stay,total:walking+stay,walk,legs}}
function skipSavingMinutes(plan,index){const pos=plan.legs.findIndex(x=>x.index===index);if(pos<0||index>=plan.endIndex)return 0;const item=plan.legs[pos],prev=pos===0?(state.currentPos||null):state.stops[plan.legs[pos-1].index],next=state.stops[plan.legs[pos+1]?.index];let detour=0;if(prev&&next&&Number.isFinite(+prev.lat)&&Number.isFinite(+prev.lon)&&Number.isFinite(+next.lat)&&Number.isFinite(+next.lon)){const via=hav(prev,{lat:+item.lat||+state.stops[index].lat,lon:+item.lon||+state.stops[index].lon})+hav(state.stops[index],next),direct=hav(prev,next);detour=Math.max(0,(via-direct)/1000/plan.walk*60)}return Math.max(0,Math.round((item.stay||0)+detour))}
function deadlineValues(){const deadline=$('cDeadline')?.value||timeValue(new Date(Date.now()+2*3600000)),dayOffset=Math.max(0,+($('cDeadlineDay')?.value)||0),buffer=Math.max(0,+($('cEventBuffer')?.value)||0),targetIndex=+($('cTargetStop')?.value??state.currentStopIndex),rawMinutes=minutesUntilTime(deadline,dayOffset),expired=rawMinutes<=0,available=Math.max(0,rawMinutes-buffer),bufferExpired=!expired&&available<=0,plan=remainingPlan(targetIndex),slack=Math.round(available-plan.total),walkMinutes=Math.max(1,available-plan.stay),requiredSpeed=plan.totalDistance/1000/(walkMinutes/60);return{deadline,dayOffset,buffer,rawMinutes,expired,bufferExpired,available,plan,slack,requiredSpeed}}
function calculatorValues(context=null){const base=dateFromTime($('cBaseTime')?.value);if(context?.timeFieldMode)return{base,distance:0,speed:0,stay:0,buffer:0,travel:0,arrival:new Date(base),leave:new Date(base),total:0};return deadlineValues()}
function calcHistoryHtml(context){const history=loadCalcHistory();if(!history.length)return'<p class="note">尚無計算紀錄。</p>';return history.map((h,i)=>{if(h.mode==='deadline')return`<article class="history-card"><div><strong>${h.dayOffset?'明天 ':'今天 '}${esc(h.deadline)} 前抵達｜${h.slack>=0?`尚餘 ${h.slack} 分鐘`:`不足 ${Math.abs(h.slack)} 分鐘`}</strong><small>${esc(h.createdLabel)}｜${esc(h.targetName||'指定地點')}｜可用 ${h.available} 分鐘</small></div><div class="history-actions"><button data-history-load="${i}">載入</button></div></article>`;return`<article class="history-card"><div><strong>${esc(h.arrival)}${h.mode==='time-field'?'':' 抵達'}${h.mode==='time-field'?'':`｜${esc(h.leave)} 離開`}</strong><small>${esc(h.createdLabel)}｜起算 ${esc(h.base)}${h.mode==='time-field'?'｜時間欄位調整':`｜總計 ${h.total} 分鐘`}</small></div><div class="history-actions"><button data-history-load="${i}">載入</button>${context?.onApply?`<button data-history-apply="${i}">直接套用</button>`:''}</div></article>`}).join('')}
function renderCalculatorHistory(context){const el=$('calcHistory');if(!el)return;el.innerHTML=calcHistoryHtml(context);el.querySelectorAll('[data-history-load]').forEach(b=>b.onclick=()=>{const h=loadCalcHistory()[+b.dataset.historyLoad];if(!h)return;if(h.mode==='deadline'&&!context?.timeFieldMode){$('cDeadline').value=h.deadline;if($('cDeadlineBtn'))$('cDeadlineBtn').textContent=h.deadline;if($('cTargetStop'))$('cTargetStop').value=h.targetIndex??state.currentStopIndex}else{$('cBaseTime').value=h.base}renderCalculatorPreview(context)});el.querySelectorAll('[data-history-apply]').forEach(b=>b.onclick=()=>{const h=loadCalcHistory()[+b.dataset.historyApply];if(h&&context?.onApply)context.onApply(h.arrival)})}
function deadlineAdvice(v){if(v.expired)return'<div class="deadline-advice bad"><strong>截止時間已過</strong><span>請重新選擇今天較晚的時間，或明確改成「明天」。系統不會再自動把過去時間當成隔天。</span></div>';if(v.bufferExpired)return'<div class="deadline-advice bad"><strong>已超過安全抵達時間</strong><span>截止時間尚未到，但扣除提前抵達緩衝後已沒有可用時間。</span></div>';if(!state.stops.length)return'<div class="viz-callout">尚未建立景點，暫時只能計算截止時間倒數。</div>';if(v.slack>=30)return'<div class="deadline-advice ok"><strong>時間充裕</strong><span>目前規劃仍有調整空間，不需要急著刪減。</span></div>';if(v.slack>=10)return'<div class="deadline-advice warn"><strong>時間偏緊</strong><span>建議減少停留或稍微加快步伐，並避免再新增景點。</span></div>';if(v.slack>=0)return'<div class="deadline-advice warn"><strong>幾乎沒有餘裕</strong><span>建議立刻前往，或跳過一個中途景點。</span></div>';return`<div class="deadline-advice bad"><strong>預估來不及</strong><span>目前規劃超出可用時間 ${Math.abs(v.slack)} 分鐘，應刪減景點或改用更快交通方式。</span></div>`}
function renderCutSuggestions(v){const box=$('cutSuggestions');if(!box)return;const choices=v.plan.legs.filter(x=>x.index<v.plan.endIndex).map(x=>({...x,saving:skipSavingMinutes(v.plan,x.index)})).filter(x=>x.saving>0).sort((a,b)=>b.saving-a.saving);if(!choices.length){box.innerHTML='<p class="note">目前沒有可刪減的中途景點。</p>';return}box.innerHTML=choices.map(x=>`<article class="cut-card"><div><strong>${esc(x.name)}</strong><small>跳過後約可節省 ${x.saving} 分鐘</small></div><button data-cut-stop="${x.index}">本次跳過</button></article>`).join('');box.querySelectorAll('[data-cut-stop]').forEach(b=>b.onclick=()=>{const i=+b.dataset.cutStop;if(confirm(`本次跳過「${state.stops[i]?.name}」？`)){skipStopAt(i);openCalculator()}})}
function renderCalculatorPreview(context){if(!$('calcResult'))return;if(context?.timeFieldMode){const v=calculatorValues(context),arrival=timeValue(v.arrival);$('calcResult').innerHTML=`<div class="detail result-focus"><small>將寫入時間欄位</small><strong>${arrival}</strong></div>`;return}const v=deadlineValues(),target=state.stops[v.plan.endIndex],invalid=v.expired||v.bufferExpired,status=invalid?'不可計算':(v.slack>=0?`尚餘 ${v.slack} 分鐘`:`不足 ${Math.abs(v.slack)} 分鐘`),speedText=!invalid&&Number.isFinite(v.requiredSpeed)?`${v.requiredSpeed.toFixed(1)} km/h`:'—';$('calcResult').innerHTML=`<div class="detail ${invalid?'danger-detail':'result-focus'}"><small>距離必須抵達時間</small><strong>${v.expired?'已過期':`${v.available} 分鐘`}</strong></div><div class="detail"><small>目前行程預估需要</small><strong>${Math.ceil(v.plan.total)} 分鐘</strong></div><div class="detail ${invalid||v.slack<0?'danger-detail':'result-focus'}"><small>時間差</small><strong>${status}</strong></div><div class="detail"><small>步行距離</small><strong>${formatDistance(v.plan.totalDistance)}</strong></div><div class="detail"><small>中途停留</small><strong>${Math.ceil(v.plan.stay)} 分鐘</strong></div><div class="detail"><small>需要平均步速</small><strong>${speedText}</strong></div><div class="detail"><small>必須抵達地點</small><strong>${esc(target?.name||'未指定')}</strong></div><div class="detail"><small>必須抵達時間</small><strong>${esc(v.deadline)}</strong></div>${deadlineAdvice(v)}`;renderCutSuggestions(v)}
function openCalculator(context=null,restore=null){const fieldMode=!!context?.timeFieldMode,now=context?.initialTime||timeValue(new Date());if(fieldMode){openDrawer(context?.title||'調整時間',`<div class="form-grid"><label>時間<input id="cBaseTime" type="time" value="${esc(now)}"></label></div><div class="quick-time"><span>快速調整時間</span><div class="quick-time-grid">${[-30,-20,-10,-5,5,10,20,30].map(n=>`<button type="button" data-shift="${n}">${n>0?'+':''}${n}</button>`).join('')}</div><div class="custom-shift"><input id="cCustomShift" type="number" inputmode="numeric" min="0" value="15" aria-label="自訂分鐘"><button id="customMinus" type="button">減少</button><button id="customPlus" type="button">增加</button></div></div><div class="button-row"><button id="calcBtn" class="primary-action">記錄並套用</button><button id="resetNow">重新帶入現在時間</button></div><div id="calcResult" class="detail-grid calc-result"></div><hr class="divider"><div class="history-head"><h3>歷史紀錄</h3><button id="clearCalcHistory" class="danger-text">清除</button></div><div id="calcHistory" class="history-list"></div>`,()=>{const recalc=()=>renderCalculatorPreview(context);document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>shiftTimeInput(+b.dataset.shift,context));$('customMinus').onclick=()=>shiftTimeInput(-Math.abs(+$('cCustomShift').value||0),context);$('customPlus').onclick=()=>shiftTimeInput(Math.abs(+$('cCustomShift').value||0),context);$('resetNow').onclick=()=>{$('cBaseTime').value=timeValue(new Date());recalc()};$('cBaseTime').addEventListener('input',recalc);$('calcBtn').onclick=()=>{const v=calculatorValues(context),arrival=timeValue(v.arrival),item={mode:'time-field',createdAt:Date.now(),createdLabel:new Date().toLocaleString('zh-TW',{hour12:false}),base:arrival,arrival,leave:arrival,total:0};saveCalcHistory(item);context?.onApply?.(arrival);showMapMessage('時間已記錄並套用','ok')};$('clearCalcHistory').onclick=()=>{if(confirm('確定清除全部時間計算紀錄？')){localStorage.removeItem(CALC_HISTORY_KEY);renderCalculatorHistory(context)}};recalc();renderCalculatorHistory(context)});return}
const remaining=state.stops.map((s,i)=>i>=state.currentStopIndex?`<option value="${i}" ${String(i)===String(restore?.targetIndex)?'selected':''}>${i+1}. ${esc(s.name)}</option>`:'').join(''),deadlineVal=restore?.deadline||timeValue(new Date(Date.now()+2*3600000));openDrawer('行程時間評估',`<p class="calc-subtitle">現在時間：${timeValue(new Date())}</p><div id="calcIntro" class="calculator-intro hidden">用途：輸入列車、表演、預約等不能錯過的時間與地點，系統比較『剩餘可用時間』和『目前行程預估所需時間』，協助判斷要不要加快、縮短停留或跳過景點。</div><div class="form-grid"><label>必須抵達時間<button type="button" id="cDeadlineBtn" class="field-button">${esc(deadlineVal)}</button><input type="hidden" id="cDeadline" value="${esc(deadlineVal)}"></label><label>必須抵達地點<select id="cTargetStop">${remaining||'<option value="0">尚無景點</option>'}</select></label></div><div class="button-row"><button id="calcBtn" class="primary-action">重新計算並記錄</button></div><div id="calcResult" class="detail-grid calc-result"></div><hr class="divider"><div class="history-head"><h3>可刪減景點</h3></div><div id="cutSuggestions" class="history-list"></div><hr class="divider"><div class="history-head"><h3>歷史紀錄</h3><button id="clearCalcHistory" class="danger-text">清除</button></div><div id="calcHistory" class="history-list"></div>`,()=>{els.drawerHelp.classList.remove('hidden');els.drawerHelp.onclick=()=>{$('calcIntro').classList.toggle('hidden')};const recalc=()=>renderCalculatorPreview(null);$('cDeadlineBtn').onclick=()=>{const targetIndex=$('cTargetStop')?.value;openDeadlineTimeEditor($('cDeadline').value,time=>openCalculator(null,{deadline:time,targetIndex}))};$('cTargetStop')?.addEventListener('input',recalc);$('calcBtn').onclick=()=>{const v=deadlineValues();if(v.expired||v.bufferExpired){showMapMessage(v.expired?'必須抵達時間已過，請重新設定':'已超過安全抵達時間','warn');return}const target=state.stops[v.plan.endIndex],item={mode:'deadline',createdAt:Date.now(),createdLabel:new Date().toLocaleString('zh-TW',{hour12:false}),deadline:v.deadline,dayOffset:0,buffer:0,targetIndex:v.plan.endIndex,targetName:target?.name||'',available:v.available,required:Math.ceil(v.plan.total),slack:v.slack};saveCalcHistory(item);recalc();renderCalculatorHistory(null);showMapMessage('已記錄行程時間評估','ok')};$('clearCalcHistory').onclick=()=>{if(confirm('確定清除全部時間計算紀錄？')){localStorage.removeItem(CALC_HISTORY_KEY);renderCalculatorHistory(null)}};recalc();renderCalculatorHistory(null)})}
function openDeadlineTimeEditor(current,onApply){openDrawer('必須抵達時間設定',`<div class="form-grid"><label>時間<input id="dTime" type="time" value="${esc(current)}"></label></div><div class="quick-time"><span>快速調整</span><div class="quick-time-grid">${[-30,-20,-10,-5,5,10,20,30].map(n=>`<button type="button" data-dshift="${n}">${n>0?'+':''}${n}</button>`).join('')}</div></div><div class="button-row"><button id="applyDeadline" class="primary-action">套用</button></div>`,()=>{const shift=m=>{const d=dateFromTime($('dTime').value);d.setMinutes(d.getMinutes()+m);$('dTime').value=timeValue(d)};document.querySelectorAll('[data-dshift]').forEach(b=>b.onclick=()=>shift(+b.dataset.dshift));$('applyDeadline').onclick=()=>{onApply($('dTime').value)}})}
function fmtTime(d){return d.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}
function statusLamp(label,on,text,onClass='ok'){return `<div class="gps-status-row"><span class="mini-lamp ${on?onClass:'idle'}"></span><div><strong>${label}</strong><small>${text}</small></div></div>`}
function openGpsPanel(){const ev=evaluateRoute(),age=state.lastFix?Math.round((Date.now()-state.lastFix)/1000):null,gpsOn=!!state.watchId||!!state.simulation,fixFresh=age!=null&&age<15,wakeOn=!!state.wakeLock,voiceOn='speechSynthesis'in window;openDrawer('GPS 詳細資料',`<div class="gps-status-list">${statusLamp('定位追蹤',gpsOn,gpsOn?'已啟動':'尚未啟動')}${statusLamp('定位更新',fixFresh,age==null?'尚無定位':`${age} 秒前`,age!=null&&age<30?'ok':'warn')}${statusLamp('Wake Lock',wakeOn,wakeOn?'已啟用':'未啟用')}${statusLamp('語音功能',voiceOn,voiceOn?'瀏覽器支援':'不支援')}</div><hr class="divider"><div class="detail-grid"><div class="detail"><small>緯度</small><strong>${state.currentPos?.lat?.toFixed(6)||'—'}</strong></div><div class="detail"><small>經度</small><strong>${state.currentPos?.lon?.toFixed(6)||'—'}</strong></div><div class="detail"><small>精度</small><strong>${state.accuracy?`±${Math.round(state.accuracy)} m`:'—'}</strong></div><div class="detail"><small>更新時間</small><strong>${age==null?'—':`${age} 秒前`}</strong></div><div class="detail"><small>距離路線</small><strong>${Number.isFinite(ev.distance)?formatDistance(ev.distance):'—'}</strong></div><div class="detail"><small>路線判斷</small><strong>${ev.label}</strong></div><div class="detail"><small>速度</small><strong>${state.speed!=null?`${(state.speed*3.6).toFixed(1)} km/h`:'—'}</strong></div></div><hr class="divider"><div class="button-row"><button id="startGps">開始真實定位</button><button id="stopGps">停止定位</button><button id="copyDiag">複製診斷紀錄</button></div>`,()=>{$('startGps').onclick=()=>startTracking();$('stopGps').onclick=()=>stopTracking();$('copyDiag').onclick=()=>navigator.clipboard?.writeText(state.log.join('\n'))})}
function openSettings(){const t=getThresholds();openDrawer('設定與偏離門檻',`<div class="form-grid"><label>注意偏離（公尺）<input id="sWarn" type="number" value="${t.warn}"></label><label>偏離路線（公尺）<input id="sOff" type="number" value="${t.off}"></label><label>嚴重偏離（公尺）<input id="sBad" type="number" value="${t.bad}"></label><label>預設步行速度（km/h）<input id="sWalk" type="number" step="0.1" value="${t.walk}"><small class="field-help">4 km/h 是旅行規劃用的保守基準，不是由 GPS 自動量測。定位穩定後，預估應優先參考近期實際步速。慢走可設 3、一般 4、趕路 5。</small></label></div><div class="button-row"><button id="saveSettings">儲存設定</button><button id="testVoice">測試語音</button><button id="wakeNow">啟用 Wake Lock</button></div>`,()=>{$('saveSettings').onclick=()=>{localStorage.setItem(SETTINGS_KEY,JSON.stringify({warnM:+$('sWarn').value,offM:+$('sOff').value,badM:+$('sBad').value,walkSpeed:+$('sWalk').value}));closeDrawer();updateSummary()};$('testVoice').onclick=()=>speak('語音提醒測試');$('wakeNow').onclick=()=>requestWake('設定頁按鈕')})}
function exportBackup(){syncActiveTrip();const data={version:'11.2',exportedAt:new Date().toISOString(),trips:state.trips,activeTripId:state.activeTripId,settings:getThresholds()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`iphone-route-v11-2-backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openBackup(){openDrawer('備份與恢復',`<div class="button-row"><button id="exportBackup">匯出 JSON 備份</button><label class="file-btn">匯入 JSON 備份<input id="backupInput" type="file" accept=".json,application/json"></label></div><p class="note">V11.2 備份會包含全部行程、景點與目前使用中的行程；舊版單一行程備份也可匯入。</p>`,()=>{$('exportBackup').onclick=exportBackup;$('backupInput').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(Array.isArray(d.trips)&&d.trips.length){state.trips=d.trips;applyTrip(state.trips.find(t=>t.id===d.activeTripId)||state.trips[0]);persistTrips()}else if(Array.isArray(d.stops)){const t={id:tripId(),name:d.tripName||'匯入的舊版行程',route:d.route?.points||[],stops:d.stops,currentStopIndex:+d.currentStopIndex||0,paused:false,updatedAt:Date.now()};syncActiveTrip();state.trips.push(t);applyTrip(t);persistTrips()}else throw new Error('備份格式不正確');if(d.settings)localStorage.setItem(SETTINGS_KEY,JSON.stringify({warnM:d.settings.warn||d.settings.warnM,offM:d.settings.off||d.settings.offM,badM:d.settings.bad||d.settings.badM,walkSpeed:d.settings.walk||4}));save();renderMap(true);closeDrawer();showMapMessage('備份已恢復','ok')}catch(err){alert(err.message)}}})}
function openAbout(){openDrawer('路線提醒器資訊',`<div class="detail-grid"><div class="detail"><small>名稱</small><strong>iPhone 日本旅行路線提醒器</strong></div><div class="detail"><small>版本</small><strong>V11.2</strong></div></div><p class="note">PWA 地圖主介面版。GPS、Wake Lock、語音、路線偏離與行程時間功能均需在 iPhone 實機持續驗證。</p>`)}
function openEndPanel(){openDrawer('結束或取消行程',`<div class="form-grid"><button id="normalEnd" class="action-btn">結束本次行程並保留紀錄</button><button id="cancelProgress" class="action-btn danger">取消本次進度，保留路線與景點</button><button id="clearAll" class="action-btn danger">清除全部路線與行程資料</button></div>`,()=>{$('normalEnd').onclick=async()=>{await stopTracking();state.paused=false;save();closeDrawer();showMapMessage('本次行程已結束','ok')};$('cancelProgress').onclick=()=>{if(!confirm('取消本次進度？'))return;state.stops.forEach(s=>{s.arrived=false;s.arrivedAt=null});state.currentStopIndex=0;state.paused=false;save();renderMap();closeDrawer()};$('clearAll').onclick=async()=>{if(!confirm('清除全部行程、路線、景點與進度？此動作無法復原。'))return;await stopTracking();const t={id:tripId(),name:'未命名行程',route:[],stops:[],currentStopIndex:0,paused:false,updatedAt:Date.now()};state.trips=[t];applyTrip(t);persistTrips();save();renderMap(true);closeDrawer()}})}
function advanceStop(){let i=state.currentStopIndex+1;while(i<state.stops.length&&state.stops[i].arrived)i++;state.currentStopIndex=Math.min(i,Math.max(0,state.stops.length-1))}
function arrive(){const s=state.stops[state.currentStopIndex];if(!s)return alert('尚未設定景點');s.arrived=true;s.arrivedAt=new Date().toISOString();speak(`已抵達${s.name}`);advanceStop();save();renderMap();showMapMessage(`已記錄抵達：${s.name}`,'ok',3000)}
function enterBlack(){requestWake('進入黑畫面');els.blackScreen.classList.remove('hidden')}
function beginHold(){if(state.tracking&&!state.wakeLock)requestWake('黑畫面觸碰');const start=performance.now();holdTimer=setTimeout(()=>{els.blackScreen.classList.add('hidden');endHold()},3000);const tick=n=>{const p=Math.min(1,(n-start)/3000);els.holdRing.style.transform=`scale(${1+p*.4})`;holdAnim=requestAnimationFrame(tick)};holdAnim=requestAnimationFrame(tick)}function endHold(){clearTimeout(holdTimer);cancelAnimationFrame(holdAnim);els.holdRing.style.transform='scale(1)'}
els.blackScreen.addEventListener('pointerdown',beginHold);els.blackScreen.addEventListener('pointerup',endHold);els.blackScreen.addEventListener('pointercancel',endHold);
function simulate(action){if(!state.route.length&&action!=='near')return alert('請先匯入一條路線');state.sim=true;state.tracking=true;const q=els.simGpsQuality.value,acc={good:8,fair:32,bad:95,stale:20,off:999}[q];if(q==='off'){state.lastFix=0;state.accuracy=999;updateSummary();return}let p;if(action==='near'){const s=state.stops[state.currentStopIndex];if(!s)return alert('尚未設定下一站');p={lat:+s.lat+.00003,lon:+s.lon+.00003};state.simVoiceOverrideUntil=Date.now()+5000;speak(`接近下一站，${s.name}`);showMapMessage(`接近下一站：${s.name}`,'ok',3500)}else{if(action==='start')state.simRouteIndex=0;if(action==='advance')state.simRouteIndex=Math.min(state.route.length-1,state.simRouteIndex+Math.max(1,Math.floor(state.route.length/20)));p={...state.route[state.simRouteIndex]};if(action==='left'||action==='right'){const sign=action==='left'?1:-1;p={lat:p.lat+.0007*sign,lon:p.lon-.0007*sign}}if(action==='return'){state.simVoiceOverrideUntil=Date.now()+3000;speak('回到路線')}}state.currentPos=p;state.accuracy=acc;state.speed=1.1;state.lastFix=q==='stale'?Date.now()-60000:Date.now();renderMap();map.panTo([p.lat,p.lon])}

document.querySelectorAll('[data-sim]').forEach(b=>b.onclick=()=>simulate(b.dataset.sim));els.simDelay.onchange=()=>{state.simDelay=+els.simDelay.value||0;state.simVoiceOverrideUntil=Date.now()+3000;updateSummary();speak(state.simDelay>0?`模擬行程落後${state.simDelay}分鐘`:'模擬行程目前準時')};els.exitSimBtn.onclick=()=>{state.sim=false;state.currentPos=null;state.lastFix=0;if(currentMarker){map.removeLayer(currentMarker);currentMarker=null}if(accuracyCircle){map.removeLayer(accuracyCircle);accuracyCircle=null}stopTracking();updateSummary()};
function togglePauseByHold(){state.paused=!state.paused;save();updateSummary();showMapMessage(state.paused?'行程已暫停':'繼續行程',state.paused?'warn':'ok',2500);speak(state.paused?'行程已暫停':'繼續行程')}
let nextHoldTimer=null,nextHoldFired=false;
function beginNextHold(){nextHoldFired=false;els.nextStopCard.classList.add('holding');nextHoldTimer=setTimeout(()=>{nextHoldFired=true;els.nextStopCard.classList.remove('holding');togglePauseByHold()},900)}
function cancelNextHold(){clearTimeout(nextHoldTimer);els.nextStopCard.classList.remove('holding')}
els.nextStopCard.addEventListener('pointerdown',beginNextHold);els.nextStopCard.addEventListener('pointerup',cancelNextHold);els.nextStopCard.addEventListener('pointercancel',cancelNextHold);els.nextStopCard.addEventListener('pointerleave',cancelNextHold);
els.moreBtn.onclick=openMore;els.quickAddBtn.onclick=openAddChoice;els.arriveBtn.onclick=arrive;els.tripCalcBtn.onclick=()=>openCalculator();els.gpsIndicator.onclick=openGpsPanel;els.wakeIndicator.onclick=()=>requestWake('狀態燈號');els.voiceIndicator.onclick=()=>speak('語音功能正常');els.recenterBtn.onclick=()=>{if(state.currentPos)map.setView([state.currentPos.lat,state.currentPos.lon],17);else renderMap(true)};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.tracking&&!state.wakeLock)armWakeTap('回到前景')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(e=>log(`Service Worker 失敗：${e.message}`)));
load();initMap();updateSummary();setInterval(updateSummary,5000);log('V11.2 主畫面與行程時間評估整理版已啟動');if(new URLSearchParams(location.search).get('autostart')==='1')setTimeout(startTracking,300);
