'use strict';
const $=id=>document.getElementById(id);
const els={routeInput:$('routeInput'),startBtn:$('startBtn'),stopBtn:$('stopBtn'),wakeBtn:$('wakeBtn'),blackBtn:$('blackBtn'),clearRouteBtn:$('clearRouteBtn'),gpsQuality:$('gpsQuality'),accuracy:$('accuracy'),fixAge:$('fixAge'),distance:$('distance'),status:$('status'),wakeStatus:$('wakeStatus'),currentStop:$('currentStop'),nextStop:$('nextStop'),stopList:$('stopList'),addStopBtn:$('addStopBtn'),exportBtn:$('exportBtn'),backupInput:$('backupInput'),resetTripBtn:$('resetTripBtn'),canvas:$('routeCanvas'),warnM:$('warnM'),offM:$('offM'),badM:$('badM'),log:$('log'),copyLogBtn:$('copyLogBtn'),clearLogBtn:$('clearLogBtn'),blackScreen:$('blackScreen'),blackGps:$('blackGps'),blackStatus:$('blackStatus'),blackDistance:$('blackDistance'),blackStop:$('blackStop'),blackWake:$('blackWake'),holdRing:$('holdRing')};
const ctx=els.canvas.getContext('2d');
const ROUTE_KEY='routeWakeTest.savedRoute';
const TRIP_KEY='routeWakeTest.trip.v11';
const SETTINGS_KEY='routeWakeTest.settings';
let route=[],stops=[],currentStopIndex=0,currentPos=null,watchId=null,wakeLock=null,trackingActive=false,lastFixTime=0,ageTimer=null,lastAlertLevel='normal',lastAlertAt=0,tapWakeArmed=false,holdTimer=null,holdAnim=null;
function log(msg){const t=new Date().toLocaleTimeString('zh-TW',{hour12:false});els.log.textContent=`[${t}] ${msg}\n`+els.log.textContent}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function saveAll(){localStorage.setItem(ROUTE_KEY,JSON.stringify({version:11,savedAt:Date.now(),name:'v11 路線',points:route}));localStorage.setItem(TRIP_KEY,JSON.stringify({version:11,stops,currentStopIndex,updatedAt:Date.now()}));localStorage.setItem(SETTINGS_KEY,JSON.stringify({warnM:els.warnM.value,offM:els.offM.value,badM:els.badM.value}))}
function loadAll(){try{const r=JSON.parse(localStorage.getItem(ROUTE_KEY)||'null');if(r?.points?.length>1)route=r.points;const t=JSON.parse(localStorage.getItem(TRIP_KEY)||'null');if(t?.version===11&&Array.isArray(t.stops)){stops=t.stops;currentStopIndex=Math.min(Number(t.currentStopIndex)||0,Math.max(0,stops.length-1))}const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null');if(s){els.warnM.value=s.warnM||30;els.offM.value=s.offM||50;els.badM.value=s.badM||80}}catch(e){log('本機資料讀取失敗：'+e.message)}renderStops();draw()}
function parseXml(text){const d=new DOMParser().parseFromString(text,'application/xml');if(d.querySelector('parsererror'))throw new Error('XML 解析失敗');return d}
function textOf(n,tag){return n.getElementsByTagName(tag)[0]?.textContent?.trim()||''}
function parseGpx(text){const d=parseXml(text),pts=[],ws=[];for(const n of d.querySelectorAll('trkpt,rtept')){const lat=Number(n.getAttribute('lat')),lon=Number(n.getAttribute('lon'));if(Number.isFinite(lat)&&Number.isFinite(lon))pts.push({lat,lon})}for(const n of d.querySelectorAll('wpt')){const lat=Number(n.getAttribute('lat')),lon=Number(n.getAttribute('lon'));if(Number.isFinite(lat)&&Number.isFinite(lon))ws.push(makeStop(textOf(n,'name')||`景點 ${ws.length+1}`,lat,lon,textOf(n,'desc')))}return{points:simplify(pts),stops:ws}}
function parseKml(text){const d=parseXml(text),pts=[],ws=[];for(const line of d.getElementsByTagName('LineString')){const c=line.getElementsByTagName('coordinates')[0]?.textContent||'';for(const tok of c.trim().split(/\s+/)){const [lon,lat]=tok.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon))pts.push({lat,lon})}}for(const pm of d.getElementsByTagName('Placemark')){const point=pm.getElementsByTagName('Point')[0];if(!point)continue;const c=point.getElementsByTagName('coordinates')[0]?.textContent?.trim()||'';const [lon,lat]=c.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon))ws.push(makeStop(textOf(pm,'name')||`景點 ${ws.length+1}`,lat,lon,textOf(pm,'description')))}return{points:simplify(pts),stops:ws}}
function simplify(a){if(a.length<=3000)return a;const n=Math.ceil(a.length/3000),o=[];for(let i=0;i<a.length;i+=n)o.push(a[i]);o.push(a[a.length-1]);return o}
function makeStop(name='新景點',lat=null,lon=null,note=''){return{id:crypto.randomUUID?.()||`stop-${Date.now()}-${Math.random()}`,name,lat,lon,plannedArrival:'',stayMinutes:30,note,arrived:false,arrivedAt:null}}
function mapsUrl(s){if(Number.isFinite(s.lat)&&Number.isFinite(s.lon))return`https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lon}`;return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name||'')}`}
function renderStops(){els.stopList.innerHTML='';stops.forEach((s,i)=>{const card=document.createElement('article');card.className='stop-card'+(s.arrived?' arrived':'');card.innerHTML=`<div class="stop-head"><span class="stop-index">${i+1}</span><input class="stop-name" data-k="name" value="${escapeHtml(s.name)}"></div><div class="stop-fields"><label>預計抵達<input type="time" data-k="plannedArrival" value="${escapeHtml(s.plannedArrival||'')}"></label><label>停留分鐘<input type="number" min="0" data-k="stayMinutes" value="${Number(s.stayMinutes)||0}"></label><label>緯度<input type="number" step="any" data-k="lat" value="${Number.isFinite(s.lat)?s.lat:''}"></label><label>經度<input type="number" step="any" data-k="lon" value="${Number.isFinite(s.lon)?s.lon:''}"></label><textarea rows="3" data-k="note" placeholder="票券、入口、樓層、備註">${escapeHtml(s.note||'')}</textarea></div><div class="stop-actions"><button data-act="arrive">${s.arrived?'取消抵達':'我已抵達'}</button><a class="maps-link" href="${mapsUrl(s)}" target="_blank" rel="noopener">Google Maps</a><button data-act="up">上移</button><button data-act="down">下移</button><button data-act="delete">刪除</button></div>`;
card.addEventListener('input',e=>{const k=e.target.dataset.k;if(!k)return;s[k]=['lat','lon','stayMinutes'].includes(k)?Number(e.target.value):e.target.value;saveAll();updateStopSummary();draw()});
card.addEventListener('click',e=>{const a=e.target.dataset.act;if(!a)return;if(a==='arrive'){s.arrived=!s.arrived;s.arrivedAt=s.arrived?new Date().toISOString():null;if(s.arrived&&i===currentStopIndex)currentStopIndex=Math.min(i+1,stops.length-1)}if(a==='delete'){stops.splice(i,1);currentStopIndex=Math.min(currentStopIndex,Math.max(0,stops.length-1))}if(a==='up'&&i>0)[stops[i-1],stops[i]]=[stops[i],stops[i-1]];if(a==='down'&&i<stops.length-1)[stops[i+1],stops[i]]=[stops[i],stops[i+1]];saveAll();renderStops();draw()});els.stopList.appendChild(card)});updateStopSummary()}
function updateStopSummary(){const cur=stops[currentStopIndex];const next=stops[currentStopIndex+1];els.currentStop.textContent=cur?.name||'—';els.nextStop.textContent=next?.name||'—';els.blackStop.textContent=`下一站：${cur?.name||'—'}`}
function toRad(d){return d*Math.PI/180}function project(p,o){const R=6371000;return{x:toRad(p.lon)*R*Math.cos(toRad(o)),y:toRad(p.lat)*R}}
function nearestDistance(p){if(route.length<2)return Infinity;const pp=project(p,p.lat);let best=Infinity;for(let i=0;i<route.length-1;i++){const a=project(route[i],p.lat),b=project(route[i+1],p.lat),vx=b.x-a.x,vy=b.y-a.y,wx=pp.x-a.x,wy=pp.y-a.y,c2=vx*vx+vy*vy,t=c2?Math.max(0,Math.min(1,(vx*wx+vy*wy)/c2)):0;best=Math.min(best,Math.hypot(pp.x-(a.x+t*vx),pp.y-(a.y+t*vy)))}return best}
function evaluate(d){const w=Number(els.warnM.value)||30,o=Number(els.offM.value)||50,b=Number(els.badM.value)||80;if(!Number.isFinite(d))return['未匯入路線',''];if(d>=b)return['嚴重偏離','status-danger'];if(d>=o)return['偏離路線','status-danger'];if(d>=w)return['注意偏離','status-warn'];return['正常','status-ok']}
function speak(t){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='zh-TW';window.speechSynthesis.speak(u)}
function maybeAlert(level){const now=Date.now();if(level!==lastAlertLevel||now-lastAlertAt>20000){if(level!=='正常')speak(level);else if(lastAlertLevel!=='正常')speak('回到路線');lastAlertLevel=level;lastAlertAt=now}}
function gpsQuality(acc,age){if(age>30000)return['過舊','status-danger'];if(acc<=15)return['良好','status-ok'];if(acc<=35)return['普通','status-warn'];if(acc<=80)return['差','status-danger'];return['很差','status-danger']}
function onPosition(pos){lastFixTime=Date.now();currentPos={lat:pos.coords.latitude,lon:pos.coords.longitude};const [q,qc]=gpsQuality(pos.coords.accuracy,0);els.gpsQuality.textContent=q;els.gpsQuality.className=qc;els.accuracy.textContent=`±${Math.round(pos.coords.accuracy)} m`;els.fixAge.textContent='現在';els.blackGps.textContent=`GPS：${q} ±${Math.round(pos.coords.accuracy)}m`;const d=nearestDistance(currentPos);els.distance.textContent=Number.isFinite(d)?`${Math.round(d)} m`:'—';els.blackDistance.textContent=`距離路線：${Number.isFinite(d)?Math.round(d)+' m':'—'}`;const [st,cls]=evaluate(d);els.status.textContent=st;els.status.className=cls;els.blackStatus.textContent=st;maybeAlert(st);draw();if(!wakeLock)armTapForWakeLock('GPS 更新後')}
function onGeoError(e){log(`定位錯誤：${e.code} ${e.message}`);els.status.textContent='定位錯誤';els.status.className='status-danger'}
async function requestWakeLock(reason='手動'){if(!('wakeLock'in navigator)){setWake('不支援');return false}if(document.visibilityState!=='visible'){setWake('等待前景',true);return false}if(wakeLock)return true;try{wakeLock=await navigator.wakeLock.request('screen');setWake('已啟用');log(`Wake Lock 已啟用（${reason}）`);wakeLock.addEventListener('release',()=>{wakeLock=null;setWake(trackingActive?'點一下螢幕啟用':'未啟用',trackingActive);if(trackingActive)armTapForWakeLock('釋放後')},{once:true});return true}catch(e){setWake('點一下螢幕啟用',true);log(`Wake Lock 啟用失敗：${e.name} ${e.message}`);return false}}
function setWake(t,need=false){els.wakeStatus.textContent=t;els.wakeStatus.classList.toggle('wake-need-tap',need);els.wakeBtn.classList.toggle('need-tap',need);els.blackWake.textContent=`Wake Lock：${t}`}
function armTapForWakeLock(reason){if(tapWakeArmed||wakeLock||!trackingActive)return;tapWakeArmed=true;const h=()=>{tapWakeArmed=false;document.removeEventListener('pointerdown',h,true);if(trackingActive&&!wakeLock)requestWakeLock(`${reason}｜使用者手勢`).then(ok=>{if(!ok)armTapForWakeLock(reason)})};document.addEventListener('pointerdown',h,true);setWake('點一下螢幕啟用',true)}
async function startTracking({auto=false}={}){if(watchId!=null)return;trackingActive=true;if(!auto)await requestWakeLock('手動開始');else setWake('等第一次 GPS');watchId=navigator.geolocation.watchPosition(onPosition,onGeoError,{enableHighAccuracy:true,maximumAge:1000,timeout:15000});els.startBtn.disabled=true;els.stopBtn.disabled=false;els.status.textContent='等待 GPS';ageTimer=setInterval(()=>{if(!lastFixTime)return;const a=Date.now()-lastFixTime;els.fixAge.textContent=`${Math.round(a/1000)} 秒前`;if(a>30000){els.gpsQuality.textContent='過舊';els.gpsQuality.className='status-danger'}},5000);log(auto?'autostart 開始定位':'開始定位')}
async function stopTracking(){trackingActive=false;if(watchId!=null)navigator.geolocation.clearWatch(watchId);watchId=null;clearInterval(ageTimer);ageTimer=null;if(wakeLock){const w=wakeLock;wakeLock=null;await w.release().catch(()=>{})}setWake('未啟用');els.startBtn.disabled=false;els.stopBtn.disabled=true;els.status.textContent='已停止';log('停止定位，已釋放 Wake Lock')}
function draw(){const w=els.canvas.width,h=els.canvas.height;ctx.clearRect(0,0,w,h);const all=[...route,...stops.filter(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon)),...(currentPos?[currentPos]:[])];if(!all.length){ctx.fillStyle='#777';ctx.font='24px sans-serif';ctx.fillText('尚未匯入路線',30,50);return}const lats=all.map(p=>p.lat),lons=all.map(p=>p.lon),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),pad=35,sx=(w-pad*2)/Math.max(.00001,maxLon-minLon),sy=(h-pad*2)/Math.max(.00001,maxLat-minLat),sc=Math.min(sx,sy),xy=p=>({x:pad+(p.lon-minLon)*sc,y:h-pad-(p.lat-minLat)*sc});if(route.length>1){ctx.strokeStyle='#777';ctx.lineWidth=4;ctx.beginPath();route.forEach((p,i)=>{const q=xy(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}ctx.fillStyle='#ffd166';stops.forEach(s=>{if(!Number.isFinite(s.lat)||!Number.isFinite(s.lon))return;const q=xy(s);ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.fill()});if(currentPos){const q=xy(currentPos);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.fill()}}
function exportBackup(){const data={version:11,exportedAt:new Date().toISOString(),route:{points:route},stops,currentStopIndex,settings:{warnM:els.warnM.value,offM:els.offM.value,badM:els.badM.value}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`iphone-route-v11-backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);log('已匯出 v11 備份')}
async function importBackup(file){const d=JSON.parse(await file.text());if(d.version!==11||!Array.isArray(d.stops))throw new Error('不是有效的 v11 備份');route=d.route?.points||[];stops=d.stops;currentStopIndex=Number(d.currentStopIndex)||0;if(d.settings){els.warnM.value=d.settings.warnM||30;els.offM.value=d.settings.offM||50;els.badM.value=d.settings.badM||80}saveAll();renderStops();draw();log('已匯入 v11 備份')}
els.routeInput.addEventListener('change',async()=>{const f=els.routeInput.files[0];if(!f)return;try{const text=await f.text(),data=f.name.toLowerCase().endsWith('.kml')?parseKml(text):parseGpx(text);if(data.points.length<2)log('檔案沒有足夠路線點；仍可只使用景點資料');else route=data.points;if(data.stops.length){stops=data.stops;currentStopIndex=0}saveAll();renderStops();draw();log(`已匯入 ${f.name}：路線點 ${route.length}、景點 ${data.stops.length}`)}catch(e){alert(e.message);log('匯入失敗：'+e.message)}finally{els.routeInput.value=''}});
els.addStopBtn.onclick=()=>{stops.push(makeStop());saveAll();renderStops()};els.exportBtn.onclick=exportBackup;els.backupInput.addEventListener('change',async()=>{try{await importBackup(els.backupInput.files[0])}catch(e){alert(e.message)}finally{els.backupInput.value=''}});els.resetTripBtn.onclick=()=>{stops.forEach(s=>{s.arrived=false;s.arrivedAt=null});currentStopIndex=0;saveAll();renderStops()};els.clearRouteBtn.onclick=()=>{route=[];saveAll();draw();log('已清除路線，景點資料保留')};els.startBtn.onclick=()=>startTracking();els.stopBtn.onclick=stopTracking;els.wakeBtn.onclick=()=>requestWakeLock('按鈕');els.blackBtn.onclick=async()=>{if(trackingActive&&!wakeLock)await requestWakeLock('進入黑畫面');els.blackScreen.classList.remove('hidden')};els.copyLogBtn.onclick=()=>navigator.clipboard?.writeText(els.log.textContent);els.clearLogBtn.onclick=()=>els.log.textContent='';[els.warnM,els.offM,els.badM].forEach(x=>x.addEventListener('change',saveAll));
function beginHold(){if(trackingActive&&!wakeLock)requestWakeLock('黑畫面觸碰');const start=performance.now();holdTimer=setTimeout(()=>{els.blackScreen.classList.add('hidden');endHold(true)},3000);const tick=n=>{const p=Math.min(1,(n-start)/3000);els.holdRing.style.transform=`scale(${1+p*.35})`;els.holdRing.style.opacity=String(.35+p*.65);holdAnim=requestAnimationFrame(tick)};holdAnim=requestAnimationFrame(tick)}function endHold(done=false){clearTimeout(holdTimer);cancelAnimationFrame(holdAnim);els.holdRing.style.transform='scale(1)';els.holdRing.style.opacity='1';els.holdRing.style.borderColor=done?'#7bd88f':'#555'}
els.blackScreen.addEventListener('touchstart',beginHold,{passive:true});els.blackScreen.addEventListener('touchend',()=>endHold(false),{passive:true});els.blackScreen.addEventListener('touchcancel',()=>endHold(false),{passive:true});els.blackScreen.addEventListener('mousedown',beginHold);els.blackScreen.addEventListener('mouseup',()=>endHold(false));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&trackingActive&&!wakeLock)armTapForWakeLock('回到前景')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').then(()=>log('Service Worker 已註冊')).catch(e=>log('Service Worker 註冊失敗：'+e.message)));
loadAll();log('v11 行程資料版已啟動；GPS / Wake Lock 核心維持 v10 手勢策略。');if(new URLSearchParams(location.search).get('autostart')==='1')setTimeout(()=>startTracking({auto:true}),300);
